In [1]:
pip install numpy

In [2]:
import numpy as np
print(np.__version__)

2.1.3


In [3]:
import numpy as np
arr=np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
import numpy as n
arr=n.zeros((10,3))
arr


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
import numpy as np
arr=np.ones((5,7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [7]:
import numpy as np
arr=np.full((4,7),9)
print(arr)

[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


In [8]:
import numpy as np
arr=np.empty((5,5))
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
import numpy as np
arr=np.arange(1,100)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [13]:
import numpy as np
arr=np.arange(2,100)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


In [14]:
import numpy as np
Even=np.arange(2,200,2)
print(Even)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


In [19]:
import numpy as np
odd=np.arange(1,200)
print(odd)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199]


In [17]:
import numpy as np
arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [20]:
import numpy as np
arr=np.linspace(1,20,7)
print(arr)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [21]:
import numpy as np
arr=np.random.rand(10)
print(arr)

[0.61807481 0.81824117 0.69447836 0.37161552 0.33733606 0.34607148
 0.82068412 0.3661522  0.38286692 0.24727855]


In [22]:
import numpy as np
arr=np.random.randn(10)
print(arr)

[ 0.22481353 -0.36952474 -0.11246012  0.38131593  0.14013131 -0.21419335
 -1.25686468  0.64047822  1.00874982  0.44824945]


In [32]:
import numpy as np
arr=np.random.randint(100)
print(arr)

33


In [40]:
import numpy as np
colours=["red","green","pink","orange","blue","white","black"]
print(np.random.choice(colours,2))

['red' 'black']


In [42]:
import numpy as np
arr=np.array([1,2,3])
new=arr.copy()
new[1]=100
print("Array value is :",arr)
print("copy value is :",new)

Array value is : [1 2 3]
copy value is : [  1 100   3]


In [43]:
import numpy as np
arr=np.array([1,2,3])
new=arr.view()
new[1]=100
print("Array value is :",arr)
print("view value is :",new)

Array value is : [  1 100   3]
view value is : [  1 100   3]


In [46]:
import numpy as np
arr=np.array([5,10,15,20,25,30])
arr+=10
print("updated array value is :",arr)

updated array value is : [15 20 25 30 35 40]


In [47]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.add(A,B))

[ 7  9 11 13 15]


In [50]:
import numpy as np
A=np.array([3,5,6,7,8])
B=np.array([4,5,6,8,9])
print(np.multiply(A,B))

[12 25 36 56 72]


In [52]:
import numpy as np
A=np.array([2,7,6,5,4])
B=np.array([5,8,3,7,5,])
print(np.divide(A,B))

[0.4        0.875      2.         0.71428571 0.8       ]


In [57]:
import numpy as np
A=np.array([3,5,6,7])
B=np.array([3,6,7,4])
print(np.subtract(A,B))

[ 0 -1 -1  3]


In [60]:
import numpy as np
A=np.array([3,5,6,7,8])
B=np.array([5,6,8,4,9])
print(np.dot(A,B))

193


In [61]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(sum(arr))

45


In [63]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [64]:
import numpy as np
arr=np.array([4,6,3,8,5,9,1])
print(np.sort(arr))

[1 3 4 5 6 8 9]


In [65]:
import numpy as np
arr=np.array([1,2,3,43,5,6,7,8,3,9])
print(np.unique(arr))

[ 1  2  3  5  6  7  8  9 43]


In [70]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.ndim)
print(arr.dtype)

(9,)
9
8
1
int64


In [77]:
import numpy as np
arr=np.array([[1,2,3,4],[5,4,3,2]])
print(arr.shape)
print(arr.ndim)
print(arr[0,1])
print(arr[1,1])
print(arr[:,1])

(2, 4)
2
2
4
[2 4]


In [84]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,99,10,11,12,13,14,15])
print("Original Array",arr)
new = arr.reshape(5,3)
print(new)

Original Array [ 1  2  3  4  5  6  7  8 99 10 11 12 13 14 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 99]
 [10 11 12]
 [13 14 15]]
